spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.6.110:3306/seata_repo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: sample-repo-service
mybatis:
  mapper-locations: classpath*:com/example/repo/dal/mappers/*.xml
  type-alias-packages: com.example.repo.das.entities
dubbo:
  application:
    name: sample-repo-service
  registry:
    address: nacos://192.168.6.111:8848,nacos://192.168.6.111:8848,nacos://192.168.6.111:8848
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.example.repo.service.impl

seata:
  enabled: true
  tx-service-group: sample-repo-service
#  transport:
#    type: TCP
#    server: NIO
#    hearbeat: true
#    enable-client-batch-send-request: true
#    thread-factory:
#      boss-trhead-prefix: NettyBoss
#      workder-thread-prefix: NettyServerNIOWorkder
#      server-executor-thread-prefix: NettyServerBizHandler
#      share-boss-workder: false
#      client-selector-thread-prefix: NettyClientSelector
#      client-selector-thread-size: 1
#      client-workder-thread-prefix: NettyClientWorkderThread
#      boss-thread-size: 1
#      workder-thread-size: 8
#    shutdown:
#      wait: 3
#    serialization: seata
#    compressor: none
#  service:
#    vgroup-mapping: default
#    enable-degrade: false
#    disable-global-transaction: false
#    #grouplist: 192.168.6.110:8091
  client:
#    rm:
#      lock:
#        lock-retry-interval: 10
#        lock-retry-policy-branch-rollback-on-conflict: true
#        lock-retry-times: 30
#      rm-async-commit-buffer-limit: 10000
#      rm-async-retry-count: 5
#      rm-table-meta-check-enable: false
#      rm-report-success-enable: true
#      tm-commit-retry-count: 5
#      tm-rollback-retry-count: 5
#      undo:
#        undo-log-table: undo_log
#        undo-data-validation: true
#        undo-log-serialization: jackson
#      log:
#        exception-rate: 100
    support:
       spring:
         datasource-autoproxy: true
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr: 192.168.6.111:8848,192.168.6.112:8848,192.168.6.113:8848