spring:
  application:
    name: sample-rest-web

dubbo:
  registry:
    address: nacos://192.168.6.111:8848,nacos://192.168.6.112:8848,nacos://192.168.6.113:8848
  scan:
    base-packages: com.example.web.service.impl

seata:
  enable: true
  tx-service-group: sample-rest-web
  transport:
    type: TCP
    server: NIO
    heartbeat: true
    enable-client-batch-send-request: true
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NEttyServerBizHandler
      share-boss-workder: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-workder-thread-prefix: NettyClientWorkderThread
      boss-thread-size: 1
      worker-thread-size: 8
    shutdown:
      wait: 3
    serialization: seata
    compressor: none
  service:
    vgroup-mapping: default
    enable-degrade: false
    disable-global-transaction: false
    #grouplist: 192.168.6.110:8091
  client:
    rm:
      lock:
        lock-retry-interval: 10
        lock-retry-policy-branch-rollback-on-conflict: true
        lock-retry-times: 30
    rm-async-commit-buffer-limit: 10000
    rm-report-retry-count: 5
    rm-table-meta-check-enable: false
    rm-report-success-enable: true
    tm-commit-retry-count: 5
    tm-rollback-retry-count: 5
    undo:
      undo-log-table: undo_log
      undo-data-validation: true
      undo-log-serialization: jackson
    log:
      exception-rate: 100
    support:
      spring:
        datasource-autoproxy: false
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr: 192.168.6.111:8848,192.168.6.112:8848,192.168.6.113:8848